# eksctl create cluster -f cluster-two.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jds2
  region: us-east-1

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-031b62368a69dd7c1 }
      us-east-1b: { id: subnet-0d21ffae363f3e3e1 }
    private:
      us-east-1a: { id: subnet-02a134e8271e52f52 }
      us-east-1b: { id: subnet-06516e48dd5b83b06 }

# if you use a yaml config file you have to specify managedNodeGroups
# or you will get unmanaged.
managedNodeGroups:
  - name: one
    # instanceType: m5.large
    # desiredCapacity: 3
    # volumeSize: 80
    # privateNetworking must be explicitly set for a fully-private cluster
    # Rather than defaulting this field to `true`,
    # we require users to explicitly set it to make the behaviour
    # explicit and avoid confusion.
    # privateNetworking: true
    # ssh:
    #   publicKeyPath: ~/.ssh/id_ecdsa.pub
      # allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: two
    # instanceType: m5.xlarge
    # desiredCapacity: 2
    # volumeSize: 100
    # privateNetworking: true
    # ssh:
    #   publicKeyPath: ~/.ssh/id_ecdsa.pub
