# eksctl create cluster -f cluster-one.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jds1
  region: us-east-1

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-04a9d30e35bb8afa6 }
      us-east-1b: { id: subnet-0502f7160c85e8124 }
    private:
      us-east-1a: { id: subnet-0dc9cc6cc9cb1b550 }
      us-east-1b: { id: subnet-05c43c7863257524f }

# if you use a yaml config file you have to specify managedNodeGroups
# or you will get unmanaged.
managedNodeGroups:
  - name: one
    # instanceType: m5.large
    # desiredCapacity: 3
    # volumeSize: 80
    # privateNetworking must be explicitly set for a fully-private cluster
    # Rather than defaulting this field to `true`,
    # we require users to explicitly set it to make the behaviour
    # explicit and avoid confusion.
    # privateNetworking: true
    # ssh:
    #   publicKeyPath: ~/.ssh/id_ecdsa.pub
      # allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: two
    # instanceType: m5.xlarge
    # desiredCapacity: 2
    # volumeSize: 100
    # privateNetworking: true
    # ssh:
    #   publicKeyPath: ~/.ssh/id_ecdsa.pub
